export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST'; //nome da ação
export const BOTAO_CLICADO_SUCESS = 'BOTAO_CLICADO_SUCESS'; //nome da ação
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE'; //nome da ação

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_UPDATED_SUCCESS';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_CREATED_SUCCESS';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
